# Autogenerated wrapper script for Qt6Quick3D_jll for aarch64-apple-darwin
export libqt6quick3d, libqt6quick3dassetimport, libqt6quick3dassetutils, libqt6quick3deffects, libqt6quick3dglslparser, libqt6quick3dhelpers, libqt6quick3dhelpersimpl, libqt6quick3diblbaker, libqt6quick3dparticleeffects, libqt6quick3dparticles, libqt6quick3druntimerender, libqt6quick3dutils

using Qt6Base_jll
using Qt6Declarative_jll
using Qt6ShaderTools_jll
using Qt6QuickTimeline_jll
JLLWrappers.@generate_wrapper_header("Qt6Quick3D")
JLLWrappers.@declare_library_product(libqt6quick3d, "@rpath/QtQuick3D")
JLLWrappers.@declare_library_product(libqt6quick3dassetimport, "@rpath/QtQuick3DAssetImport")
JLLWrappers.@declare_library_product(libqt6quick3dassetutils, "@rpath/QtQuick3DAssetUtils")
JLLWrappers.@declare_library_product(libqt6quick3deffects, "@rpath/QtQuick3DEffects")
JLLWrappers.@declare_library_product(libqt6quick3dglslparser, "@rpath/QtQuick3DGlslParser")
JLLWrappers.@declare_library_product(libqt6quick3dhelpers, "@rpath/QtQuick3DHelpers")
JLLWrappers.@declare_library_product(libqt6quick3dhelpersimpl, "@rpath/QtQuick3DHelpersImpl")
JLLWrappers.@declare_library_product(libqt6quick3diblbaker, "@rpath/QtQuick3DIblBaker")
JLLWrappers.@declare_library_product(libqt6quick3dparticleeffects, "@rpath/QtQuick3DParticleEffects")
JLLWrappers.@declare_library_product(libqt6quick3dparticles, "@rpath/QtQuick3DParticles")
JLLWrappers.@declare_library_product(libqt6quick3druntimerender, "@rpath/QtQuick3DRuntimeRender")
JLLWrappers.@declare_library_product(libqt6quick3dutils, "@rpath/QtQuick3DUtils")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll, Qt6ShaderTools_jll, Qt6QuickTimeline_jll)
    JLLWrappers.@init_library_product(
        libqt6quick3d,
        "lib/QtQuick3D.framework/Versions/A/QtQuick3D",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dassetimport,
        "lib/QtQuick3DAssetImport.framework/Versions/A/QtQuick3DAssetImport",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dassetutils,
        "lib/QtQuick3DAssetUtils.framework/Versions/A/QtQuick3DAssetUtils",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3deffects,
        "lib/QtQuick3DEffects.framework/Versions/A/QtQuick3DEffects",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dglslparser,
        "lib/QtQuick3DGlslParser.framework/Versions/A/QtQuick3DGlslParser",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dhelpers,
        "lib/QtQuick3DHelpers.framework/Versions/A/QtQuick3DHelpers",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dhelpersimpl,
        "lib/QtQuick3DHelpersImpl.framework/Versions/A/QtQuick3DHelpersImpl",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3diblbaker,
        "lib/QtQuick3DIblBaker.framework/Versions/A/QtQuick3DIblBaker",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dparticleeffects,
        "lib/QtQuick3DParticleEffects.framework/Versions/A/QtQuick3DParticleEffects",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dparticles,
        "lib/QtQuick3DParticles.framework/Versions/A/QtQuick3DParticles",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3druntimerender,
        "lib/QtQuick3DRuntimeRender.framework/Versions/A/QtQuick3DRuntimeRender",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dutils,
        "lib/QtQuick3DUtils.framework/Versions/A/QtQuick3DUtils",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
