# Autogenerated wrapper script for Qt6Quick3D_jll for i686-w64-mingw32-cxx11
export libqt6quick3d, libqt6quick3dassetimport, libqt6quick3dassetutils, libqt6quick3deffects, libqt6quick3dglslparser, libqt6quick3dhelpers, libqt6quick3dhelpersimpl, libqt6quick3diblbaker, libqt6quick3dparticleeffects, libqt6quick3dparticles, libqt6quick3druntimerender, libqt6quick3dutils

using assimp_jll
using Qt6Base_jll
using Qt6Declarative_jll
using Qt6ShaderTools_jll
using Qt6QuickTimeline_jll
JLLWrappers.@generate_wrapper_header("Qt6Quick3D")
JLLWrappers.@declare_library_product(libqt6quick3d, "Qt6Quick3D.dll")
JLLWrappers.@declare_library_product(libqt6quick3dassetimport, "Qt6Quick3DAssetImport.dll")
JLLWrappers.@declare_library_product(libqt6quick3dassetutils, "Qt6Quick3DAssetUtils.dll")
JLLWrappers.@declare_library_product(libqt6quick3deffects, "Qt6Quick3DEffects.dll")
JLLWrappers.@declare_library_product(libqt6quick3dglslparser, "Qt6Quick3DGlslParser.dll")
JLLWrappers.@declare_library_product(libqt6quick3dhelpers, "Qt6Quick3DHelpers.dll")
JLLWrappers.@declare_library_product(libqt6quick3dhelpersimpl, "Qt6Quick3DHelpersImpl.dll")
JLLWrappers.@declare_library_product(libqt6quick3diblbaker, "Qt6Quick3DIblBaker.dll")
JLLWrappers.@declare_library_product(libqt6quick3dparticleeffects, "Qt6Quick3DParticleEffects.dll")
JLLWrappers.@declare_library_product(libqt6quick3dparticles, "Qt6Quick3DParticles.dll")
JLLWrappers.@declare_library_product(libqt6quick3druntimerender, "Qt6Quick3DRuntimeRender.dll")
JLLWrappers.@declare_library_product(libqt6quick3dutils, "Qt6Quick3DUtils.dll")
function __init__()
    JLLWrappers.@generate_init_header(assimp_jll, Qt6Base_jll, Qt6Declarative_jll, Qt6ShaderTools_jll, Qt6QuickTimeline_jll)
    JLLWrappers.@init_library_product(
        libqt6quick3d,
        "bin\\Qt6Quick3D.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dassetimport,
        "bin\\Qt6Quick3DAssetImport.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dassetutils,
        "bin\\Qt6Quick3DAssetUtils.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3deffects,
        "bin\\Qt6Quick3DEffects.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dglslparser,
        "bin\\Qt6Quick3DGlslParser.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dhelpers,
        "bin\\Qt6Quick3DHelpers.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dhelpersimpl,
        "bin\\Qt6Quick3DHelpersImpl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3diblbaker,
        "bin\\Qt6Quick3DIblBaker.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dparticleeffects,
        "bin\\Qt6Quick3DParticleEffects.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dparticles,
        "bin\\Qt6Quick3DParticles.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3druntimerender,
        "bin\\Qt6Quick3DRuntimeRender.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dutils,
        "bin\\Qt6Quick3DUtils.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
