# Autogenerated wrapper script for Qt6Quick3D_jll for x86_64-linux-gnu-cxx11
export libqt6quick3d, libqt6quick3dassetimport, libqt6quick3dassetutils, libqt6quick3deffects, libqt6quick3dglslparser, libqt6quick3dhelpers, libqt6quick3dhelpersimpl, libqt6quick3diblbaker, libqt6quick3dparticleeffects, libqt6quick3dparticles, libqt6quick3druntimerender, libqt6quick3dutils

using Qt6Base_jll
using Qt6Declarative_jll
using Qt6ShaderTools_jll
using Qt6QuickTimeline_jll
JLLWrappers.@generate_wrapper_header("Qt6Quick3D")
JLLWrappers.@declare_library_product(libqt6quick3d, "libQt6Quick3D.so.6")
JLLWrappers.@declare_library_product(libqt6quick3dassetimport, "libQt6Quick3DAssetImport.so.6")
JLLWrappers.@declare_library_product(libqt6quick3dassetutils, "libQt6Quick3DAssetUtils.so.6")
JLLWrappers.@declare_library_product(libqt6quick3deffects, "libQt6Quick3DEffects.so.6")
JLLWrappers.@declare_library_product(libqt6quick3dglslparser, "libQt6Quick3DGlslParser.so.6")
JLLWrappers.@declare_library_product(libqt6quick3dhelpers, "libQt6Quick3DHelpers.so.6")
JLLWrappers.@declare_library_product(libqt6quick3dhelpersimpl, "libQt6Quick3DHelpersImpl.so.6")
JLLWrappers.@declare_library_product(libqt6quick3diblbaker, "libQt6Quick3DIblBaker.so.6")
JLLWrappers.@declare_library_product(libqt6quick3dparticleeffects, "libQt6Quick3DParticleEffects.so.6")
JLLWrappers.@declare_library_product(libqt6quick3dparticles, "libQt6Quick3DParticles.so.6")
JLLWrappers.@declare_library_product(libqt6quick3druntimerender, "libQt6Quick3DRuntimeRender.so.6")
JLLWrappers.@declare_library_product(libqt6quick3dutils, "libQt6Quick3DUtils.so.6")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll, Qt6ShaderTools_jll, Qt6QuickTimeline_jll)
    JLLWrappers.@init_library_product(
        libqt6quick3d,
        "lib/libQt6Quick3D.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dassetimport,
        "lib/libQt6Quick3DAssetImport.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dassetutils,
        "lib/libQt6Quick3DAssetUtils.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3deffects,
        "lib/libQt6Quick3DEffects.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dglslparser,
        "lib/libQt6Quick3DGlslParser.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dhelpers,
        "lib/libQt6Quick3DHelpers.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dhelpersimpl,
        "lib/libQt6Quick3DHelpersImpl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3diblbaker,
        "lib/libQt6Quick3DIblBaker.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dparticleeffects,
        "lib/libQt6Quick3DParticleEffects.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dparticles,
        "lib/libQt6Quick3DParticles.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3druntimerender,
        "lib/libQt6Quick3DRuntimeRender.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick3dutils,
        "lib/libQt6Quick3DUtils.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
